### ISSUE TITLE
A value of type 'Object?' can't be assigned to a variable of type 'List<Color>'

### ISSUE THREAD

**Issue by federico2390** [skaran921/flutter_gradient_colors#10]
Hi I have created this list:

```
List<Map<String, Object>> cardBackgroundColors = [
  {"name": "WarmFlame", "color": GradientColors.warmFlame},
  {"name": "NightFade", "color": GradientColors.nightFade},
  {"name": "SpringWarmt", "color": GradientColors.springWarmt},
  {"name": "JuicyPeach", "color": GradientColors.juicyPeach},
  {"name": "LadyLips", "color": GradientColors.ladyLips}
];
```

Now I need to access the "color" by searching inside this list the relative "name" saved, from another page, in Shared Preference.

With previous version of Flutter all works fine, but now I receive the error in title.... Why?

So, below how I use the cardBackgroundColors List:

```
_getCardColor() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String? getColor = prefs.getString('card_color_name');
    for (var colors
        in cardBackgroundColors.where((c) => c['name'] == getColor)) {
      List<Color> color = colors['color'];     <-------------- ERROR APPEAR HERE
      setState(() {
        cardBackgroundColor = color;
      });
    }
  }
```

Thx.

**Comment by skaran921** [comment]
try this : 
     _getCardColor() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String? getColor = prefs.getString('card_color_name');
    for (var colors
        in cardBackgroundColors.where((c) => c['name'] == getColor)) {
      List<Color> color = c['color']; 
      setState(() {
        cardBackgroundColor = color;
      });
    }
  }

**Comment by federico2390** [comment]
@skaran921 Thx u!
