### ISSUE TITLE
The argument type 'List<Color>' can't be assigned to the parameter type 'Color?'.

### ISSUE THREAD

**Issue by himanshurahi1996** [skaran921/flutter_gradient_colors#9]
Getting error :
`return Container(
          padding: const EdgeInsets.all(15),
          child: Text(category.title.toString()),
          decoration: BoxDecoration(
            color: GradientColors.red,
            borderRadius: BorderRadius.circular(15),
          ),
    );`

**The argument type 'List<Color>' can't be assigned to the parameter type 'Color?'.**

**Comment by skaran921** [comment]
Hi @himanshurahi  use this  code 
BoxDecoration(
              borderRadius: BorderRadius.circular(15),
              gradient: LinearGradient(
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
              colors: GradientColors.red
     )
